# Generated by Django 5.0.2 on 2024-02-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_timline_interiors_timeline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exteriors",
            name="second_image",
        ),
        migrations.RemoveField(
            model_name="exteriors",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="exteriors",
            name="third_image",
        ),
        migrations.AlterField(
            model_name="exteriors",
            name="main_image",
            field=models.ImageField(upload_to="exteriors/"),
        ),
        migrations.CreateModel(
            name="ExteriorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="exterior_images/")),
                (
                    "description",
                    models.CharField(default="Your default value here", max_length=255),
                ),
                (
                    "exterior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.exteriors"
                    ),
                ),
            ],
        ),
    ]
